apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldp-agent
  namespace: ngd-ngg-system
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
  selector:
    matchLabels:
      app: ngd-ngg-lldp-agent
  template:
    metadata:
      labels:
        app: ngd-ngg-lldp-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 5
      serviceAccountName: lldp-agent
      containers:
      - name: lldp-agent
        image: ngd-ngg-lldp-agent:v0.2.0
        imagePullPolicy: IfNotPresent
        args:
        - --timeout=65s
        - --count=0
        - --interval=180s
        - --sys-class-net=/host-sys/class/net
        - --interfaces=bond0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 10m
            memory: 24Mi
          limits:
            cpu: 100m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
            add: ["NET_RAW"]
        volumeMounts:
        - name: host-sys
          mountPath: /host-sys
          readOnly: true
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
