apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldp-agent
  namespace: ngd-ngg-system
spec:
  template:
    spec:
      containers:
      - name: lldp-agent
        args:
        - --mode=LLDP
        - --listen-seconds=35
        - --topology-config=/etc/ngd-ngg/topology.json
