ARG TARGETARCH
ARG RELEASE_VERSION=dev

# PRC Go binary is cross-compiled before this image packaging step.
FROM scratch
ARG TARGETARCH
ARG RELEASE_VERSION
ARG VCS_REF=unknown
LABEL org.opencontainers.image.title="NGD-NGG PRC" \
      org.opencontainers.image.version="${RELEASE_VERSION}" \
      org.opencontainers.image.revision="${VCS_REF}" \
      org.opencontainers.image.source="https://hub.docker.com/r/ghwdsl/ngd-ngg-scheduling"
COPY build/release/${RELEASE_VERSION}/linux-${TARGETARCH}/prc /prc
USER 65532:65532
ENTRYPOINT ["/prc"]
