apiVersion: v1
kind: Namespace
metadata:
  name: ngd-ngg-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lldp-agent
  namespace: ngd-ngg-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngd-ngg-lldp-agent
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngd-ngg-lldp-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngd-ngg-lldp-agent
subjects:
- kind: ServiceAccount
  name: lldp-agent
  namespace: ngd-ngg-system
