---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lldp-agent
  namespace: welkin-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngd-ngg-lldp-agent
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngd-ngg-lldp-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ngd-ngg-lldp-agent
subjects:
- kind: ServiceAccount
  name: lldp-agent
  namespace: welkin-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldp-agent
  namespace: welkin-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ngd-ngg-lldp-agent
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngd-ngg-lldp-agent
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --timeout=65s
        - --count=0
        - --interval=180s
        - --sys-class-net=/host-sys/class/net
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KUBERNETES_SERVICE_HOST
          value: 10.129.195.155
        - name: KUBERNETES_SERVICE_PORT
          value: '6443'
        image: hlcsq-registry.cucloud.cn/paas/scheduling/lldp:v0.6.2
        imagePullPolicy: IfNotPresent
        name: lldp-agent
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_RAW
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host-sys
          name: host-sys
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccount: lldp-agent
      serviceAccountName: lldp-agent
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: virtual-kubelet.io/provider
        operator: Equal
        value: dubhe
      volumes:
      - hostPath:
          path: /sys
          type: Directory
        name: host-sys
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
