//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerStatus) DeepCopyInto(out *ConsumerStatus) {
	*out = *in
	if in.Used != nil {
		in, out := &in.Used, &out.Used
		*out = new(ResourceUsage)
		**out = **in
	}
	if in.Drain != nil {
		in, out := &in.Drain, &out.Drain
		*out = new(DrainStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerStatus.
func (in *ConsumerStatus) DeepCopy() *ConsumerStatus {
	if in == nil {
		return nil
	}
	out := new(ConsumerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossClusterAffinity) DeepCopyInto(out *CrossClusterAffinity) {
	*out = *in
	if in.IPList != nil {
		in, out := &in.IPList, &out.IPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossClusterAffinity.
func (in *CrossClusterAffinity) DeepCopy() *CrossClusterAffinity {
	if in == nil {
		return nil
	}
	out := new(CrossClusterAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DrainStatus) DeepCopyInto(out *DrainStatus) {
	*out = *in
	if in.Blockers != nil {
		in, out := &in.Blockers, &out.Blockers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DrainStatus.
func (in *DrainStatus) DeepCopy() *DrainStatus {
	if in == nil {
		return nil
	}
	out := new(DrainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntraClusterAffinity) DeepCopyInto(out *IntraClusterAffinity) {
	*out = *in
	if in.IPList != nil {
		in, out := &in.IPList, &out.IPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntraClusterAffinity.
func (in *IntraClusterAffinity) DeepCopy() *IntraClusterAffinity {
	if in == nil {
		return nil
	}
	out := new(IntraClusterAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkReachability) DeepCopyInto(out *NetworkReachability) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkReachability.
func (in *NetworkReachability) DeepCopy() *NetworkReachability {
	if in == nil {
		return nil
	}
	out := new(NetworkReachability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupDemand) DeepCopyInto(out *NodeGroupDemand) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupDemand.
func (in *NodeGroupDemand) DeepCopy() *NodeGroupDemand {
	if in == nil {
		return nil
	}
	out := new(NodeGroupDemand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupDemand) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupDemandList) DeepCopyInto(out *NodeGroupDemandList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeGroupDemand, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupDemandList.
func (in *NodeGroupDemandList) DeepCopy() *NodeGroupDemandList {
	if in == nil {
		return nil
	}
	out := new(NodeGroupDemandList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupDemandList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupDemandSpec) DeepCopyInto(out *NodeGroupDemandSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyLabels != nil {
		in, out := &in.TopologyLabels, &out.TopologyLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxNodes != nil {
		in, out := &in.MaxNodes, &out.MaxNodes
		*out = new(int32)
		**out = **in
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(ResourceRequirements)
		**out = **in
	}
	if in.CrossClusterAffinity != nil {
		in, out := &in.CrossClusterAffinity, &out.CrossClusterAffinity
		*out = new(CrossClusterAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.IntraClusterAffinity != nil {
		in, out := &in.IntraClusterAffinity, &out.IntraClusterAffinity
		*out = new(IntraClusterAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.MinResources != nil {
		in, out := &in.MinResources, &out.MinResources
		*out = new(ResourceRequirements)
		**out = **in
	}
	if in.NetworkReachability != nil {
		in, out := &in.NetworkReachability, &out.NetworkReachability
		*out = new(NetworkReachability)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupDemandSpec.
func (in *NodeGroupDemandSpec) DeepCopy() *NodeGroupDemandSpec {
	if in == nil {
		return nil
	}
	out := new(NodeGroupDemandSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupDemandStatus) DeepCopyInto(out *NodeGroupDemandStatus) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupDemandStatus.
func (in *NodeGroupDemandStatus) DeepCopy() *NodeGroupDemandStatus {
	if in == nil {
		return nil
	}
	out := new(NodeGroupDemandStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupGrant) DeepCopyInto(out *NodeGroupGrant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupGrant.
func (in *NodeGroupGrant) DeepCopy() *NodeGroupGrant {
	if in == nil {
		return nil
	}
	out := new(NodeGroupGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupGrant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupGrantList) DeepCopyInto(out *NodeGroupGrantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeGroupGrant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupGrantList.
func (in *NodeGroupGrantList) DeepCopy() *NodeGroupGrantList {
	if in == nil {
		return nil
	}
	out := new(NodeGroupGrantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeGroupGrantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupGrantNode) DeepCopyInto(out *NodeGroupGrantNode) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(NodeResources)
		**out = **in
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(NodeTopology)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupGrantNode.
func (in *NodeGroupGrantNode) DeepCopy() *NodeGroupGrantNode {
	if in == nil {
		return nil
	}
	out := new(NodeGroupGrantNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupGrantSpec) DeepCopyInto(out *NodeGroupGrantSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeGroupGrantNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupGrantSpec.
func (in *NodeGroupGrantSpec) DeepCopy() *NodeGroupGrantSpec {
	if in == nil {
		return nil
	}
	out := new(NodeGroupGrantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroupGrantStatus) DeepCopyInto(out *NodeGroupGrantStatus) {
	*out = *in
	if in.ResolvedCapacity != nil {
		in, out := &in.ResolvedCapacity, &out.ResolvedCapacity
		*out = new(ResolvedCapacity)
		**out = **in
	}
	if in.Consumer != nil {
		in, out := &in.Consumer, &out.Consumer
		*out = new(ConsumerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroupGrantStatus.
func (in *NodeGroupGrantStatus) DeepCopy() *NodeGroupGrantStatus {
	if in == nil {
		return nil
	}
	out := new(NodeGroupGrantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeTopology) DeepCopyInto(out *NodeTopology) {
	*out = *in
	if in.NetworkReachable != nil {
		in, out := &in.NetworkReachable, &out.NetworkReachable
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeTopology.
func (in *NodeTopology) DeepCopy() *NodeTopology {
	if in == nil {
		return nil
	}
	out := new(NodeTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedCapacity) DeepCopyInto(out *ResolvedCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedCapacity.
func (in *ResolvedCapacity) DeepCopy() *ResolvedCapacity {
	if in == nil {
		return nil
	}
	out := new(ResolvedCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUsage) DeepCopyInto(out *ResourceUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUsage.
func (in *ResourceUsage) DeepCopy() *ResourceUsage {
	if in == nil {
		return nil
	}
	out := new(ResourceUsage)
	in.DeepCopyInto(out)
	return out
}
